/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.util.Date;
import model.service.DateService;
import model.service.MenuServices;
import model.service.TableService;

/**
 *
 * @author rubens
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    public Program() {
        initComponents();
        this.pnlHome.setVisible(true);
        this.pnlSaldoBancario.setVisible(false);
        DateService dateService = new DateService();
        jXDatePicker1.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnPD000 = new rojerusan.RSButtonHover();
        grupoMenuProducao = new com.xzq.osc.JocGroupPane();
        btnPD001 = new rojerusan.RSButtonHover();
        grupoSubMenuInjetora = new com.xzq.osc.JocGroupPane();
        btnPD003 = new rojerusan.RSButtonHover();
        btnPD004 = new rojerusan.RSButtonHover();
        btnPD002 = new rojerusan.RSButtonHover();
        grupoSubMenuEmbalagem = new com.xzq.osc.JocGroupPane();
        btnPD005 = new rojerusan.RSButtonHover();
        btnPD006 = new rojerusan.RSButtonHover();
        btnET000 = new rojerusan.RSButtonHover();
        grupoMenuEstoque = new com.xzq.osc.JocGroupPane();
        btnET001 = new rojerusan.RSButtonHover();
        btnET002 = new rojerusan.RSButtonHover();
        btnET003 = new rojerusan.RSButtonHover();
        btnET004 = new rojerusan.RSButtonHover();
        btnFC000 = new rojerusan.RSButtonHover();
        grupoMenuFinanceiro = new com.xzq.osc.JocGroupPane();
        btnFC001 = new rojerusan.RSButtonHover();
        grupoSubMenuTitulos = new com.xzq.osc.JocGroupPane();
        btnFC003 = new rojerusan.RSButtonHover();
        btnFC004 = new rojerusan.RSButtonHover();
        btnFC002 = new rojerusan.RSButtonHover();
        grupoSubMenuBoletos = new com.xzq.osc.JocGroupPane();
        btnFC005 = new rojerusan.RSButtonHover();
        btnFC006 = new rojerusan.RSButtonHover();
        btnFC007 = new rojerusan.RSButtonHover();
        grupoSubMenuBancos = new com.xzq.osc.JocGroupPane();
        btnFC008 = new rojerusan.RSButtonHover();
        btnMT000 = new rojerusan.RSButtonHover();
        grupoMenuManutencao = new com.xzq.osc.JocGroupPane();
        btnMT001 = new rojerusan.RSButtonHover();
        btnMT002 = new rojerusan.RSButtonHover();
        btnMT003 = new rojerusan.RSButtonHover();
        btnMT004 = new rojerusan.RSButtonHover();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlSaldoBancario = new javax.swing.JPanel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        btnFC008Editar = new rojerusan.RSButtonHover();
        btnFC008Salvar = new rojerusan.RSButtonHover();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFC008 = new javax.swing.JTable();
        btnFC008Consultar = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1238, 717));

        pnlPrincipal.setBackground(new java.awt.Color(56, 61, 70));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setBorder(null);
        pnlMenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlMenu.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        pnlMenu.setWheelScrollingEnabled(false);

        jPanel2.setBackground(new java.awt.Color(56, 61, 70));

        btnPD000.setBackground(new java.awt.Color(56, 61, 70));
        btnPD000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_deployment_40px.png"))); // NOI18N
        btnPD000.setText("Produção");
        btnPD000.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD000.setFocusPainted(false);
        btnPD000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD000.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD000.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPD000ActionPerformed(evt);
            }
        });

        grupoMenuProducao.setDrawBorder(false);
        grupoMenuProducao.setExpanded(false);
        grupoMenuProducao.setTitleBarVisible(false);

        btnPD001.setBackground(new java.awt.Color(56, 61, 70));
        btnPD001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnPD001.setText("Injetora");
        btnPD001.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD001.setFocusPainted(false);
        btnPD001.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD001.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD001.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD001.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnPD001.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnPD001.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnPD001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPD001ActionPerformed(evt);
            }
        });

        grupoSubMenuInjetora.setDrawBorder(false);
        grupoSubMenuInjetora.setExpanded(false);
        grupoSubMenuInjetora.setTitleBarVisible(false);

        btnPD003.setBackground(new java.awt.Color(56, 61, 70));
        btnPD003.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnPD003.setText("Consultar Programação");
        btnPD003.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD003.setFocusPainted(false);
        btnPD003.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD003.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD003.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD003.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD003.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD003.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        btnPD004.setBackground(new java.awt.Color(56, 61, 70));
        btnPD004.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnPD004.setText("Criar Programação");
        btnPD004.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD004.setFocusPainted(false);
        btnPD004.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD004.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD004.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD004.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD004.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD004.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        javax.swing.GroupLayout grupoSubMenuInjetoraLayout = new javax.swing.GroupLayout(grupoSubMenuInjetora);
        grupoSubMenuInjetora.setLayout(grupoSubMenuInjetoraLayout);
        grupoSubMenuInjetoraLayout.setHorizontalGroup(
            grupoSubMenuInjetoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPD003, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPD004, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoSubMenuInjetoraLayout.setVerticalGroup(
            grupoSubMenuInjetoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoSubMenuInjetoraLayout.createSequentialGroup()
                .addComponent(btnPD003, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPD004, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnPD002.setBackground(new java.awt.Color(56, 61, 70));
        btnPD002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnPD002.setText("Embalagem");
        btnPD002.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD002.setFocusPainted(false);
        btnPD002.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD002.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD002.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD002.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnPD002.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnPD002.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnPD002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPD002ActionPerformed(evt);
            }
        });

        grupoSubMenuEmbalagem.setDrawBorder(false);
        grupoSubMenuEmbalagem.setExpanded(false);
        grupoSubMenuEmbalagem.setTitleBarVisible(false);

        btnPD005.setBackground(new java.awt.Color(56, 61, 70));
        btnPD005.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnPD005.setText("Consultar Programação");
        btnPD005.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD005.setFocusPainted(false);
        btnPD005.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD005.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD005.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD005.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD005.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD005.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        btnPD006.setBackground(new java.awt.Color(56, 61, 70));
        btnPD006.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnPD006.setText("Criar Programação");
        btnPD006.setColorHover(new java.awt.Color(87, 94, 108));
        btnPD006.setFocusPainted(false);
        btnPD006.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPD006.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPD006.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPD006.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD006.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnPD006.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        javax.swing.GroupLayout grupoSubMenuEmbalagemLayout = new javax.swing.GroupLayout(grupoSubMenuEmbalagem);
        grupoSubMenuEmbalagem.setLayout(grupoSubMenuEmbalagemLayout);
        grupoSubMenuEmbalagemLayout.setHorizontalGroup(
            grupoSubMenuEmbalagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPD005, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPD006, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoSubMenuEmbalagemLayout.setVerticalGroup(
            grupoSubMenuEmbalagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoSubMenuEmbalagemLayout.createSequentialGroup()
                .addComponent(btnPD005, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPD006, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout grupoMenuProducaoLayout = new javax.swing.GroupLayout(grupoMenuProducao);
        grupoMenuProducao.setLayout(grupoMenuProducaoLayout);
        grupoMenuProducaoLayout.setHorizontalGroup(
            grupoMenuProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPD001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grupoSubMenuInjetora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPD002, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grupoSubMenuEmbalagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoMenuProducaoLayout.setVerticalGroup(
            grupoMenuProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoMenuProducaoLayout.createSequentialGroup()
                .addComponent(btnPD001, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoSubMenuInjetora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPD002, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoSubMenuEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnET000.setBackground(new java.awt.Color(56, 61, 70));
        btnET000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_new_product_40px.png"))); // NOI18N
        btnET000.setText("Estoque");
        btnET000.setColorHover(new java.awt.Color(87, 94, 108));
        btnET000.setFocusPainted(false);
        btnET000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnET000.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnET000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnET000ActionPerformed(evt);
            }
        });

        grupoMenuEstoque.setDrawBorder(false);
        grupoMenuEstoque.setExpanded(false);
        grupoMenuEstoque.setTitleBarVisible(false);

        btnET001.setBackground(new java.awt.Color(56, 61, 70));
        btnET001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnET001.setText("Inventário");
        btnET001.setColorHover(new java.awt.Color(87, 94, 108));
        btnET001.setFocusPainted(false);
        btnET001.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnET001.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnET001.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnET001.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET001.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET001.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        btnET002.setBackground(new java.awt.Color(56, 61, 70));
        btnET002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnET002.setText("Conferência");
        btnET002.setColorHover(new java.awt.Color(87, 94, 108));
        btnET002.setFocusPainted(false);
        btnET002.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnET002.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnET002.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnET002.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET002.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET002.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        btnET003.setBackground(new java.awt.Color(56, 61, 70));
        btnET003.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnET003.setText("Consultar");
        btnET003.setColorHover(new java.awt.Color(87, 94, 108));
        btnET003.setFocusPainted(false);
        btnET003.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnET003.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnET003.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnET003.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET003.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET003.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        btnET004.setBackground(new java.awt.Color(56, 61, 70));
        btnET004.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnET004.setText("Exportação");
        btnET004.setColorHover(new java.awt.Color(87, 94, 108));
        btnET004.setFocusPainted(false);
        btnET004.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnET004.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnET004.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnET004.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET004.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnET004.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        javax.swing.GroupLayout grupoMenuEstoqueLayout = new javax.swing.GroupLayout(grupoMenuEstoque);
        grupoMenuEstoque.setLayout(grupoMenuEstoqueLayout);
        grupoMenuEstoqueLayout.setHorizontalGroup(
            grupoMenuEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnET004, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
            .addComponent(btnET003, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnET002, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnET001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoMenuEstoqueLayout.setVerticalGroup(
            grupoMenuEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoMenuEstoqueLayout.createSequentialGroup()
                .addComponent(btnET001, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnET002, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnET003, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnET004, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        btnFC000.setBackground(new java.awt.Color(56, 61, 70));
        btnFC000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_rent_40px.png"))); // NOI18N
        btnFC000.setText("Financeiro");
        btnFC000.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC000.setFocusPainted(false);
        btnFC000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC000.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC000ActionPerformed(evt);
            }
        });

        grupoMenuFinanceiro.setDrawBorder(false);
        grupoMenuFinanceiro.setExpanded(false);
        grupoMenuFinanceiro.setTitleBarVisible(false);

        btnFC001.setBackground(new java.awt.Color(56, 61, 70));
        btnFC001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnFC001.setText("Títulos");
        btnFC001.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC001.setFocusPainted(false);
        btnFC001.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC001.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC001.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC001.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC001.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC001.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC001ActionPerformed(evt);
            }
        });

        grupoSubMenuTitulos.setDrawBorder(false);
        grupoSubMenuTitulos.setExpanded(false);
        grupoSubMenuTitulos.setTitleBarVisible(false);

        btnFC003.setBackground(new java.awt.Color(56, 61, 70));
        btnFC003.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnFC003.setText("Envio para representantes");
        btnFC003.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC003.setFocusPainted(false);
        btnFC003.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC003.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC003.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC003.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC003.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC003.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        btnFC004.setBackground(new java.awt.Color(56, 61, 70));
        btnFC004.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnFC004.setText("Envio para clientes");
        btnFC004.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC004.setFocusPainted(false);
        btnFC004.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC004.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC004.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC004.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC004.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC004.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        javax.swing.GroupLayout grupoSubMenuTitulosLayout = new javax.swing.GroupLayout(grupoSubMenuTitulos);
        grupoSubMenuTitulos.setLayout(grupoSubMenuTitulosLayout);
        grupoSubMenuTitulosLayout.setHorizontalGroup(
            grupoSubMenuTitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFC003, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFC004, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoSubMenuTitulosLayout.setVerticalGroup(
            grupoSubMenuTitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoSubMenuTitulosLayout.createSequentialGroup()
                .addComponent(btnFC003, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFC004, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnFC002.setBackground(new java.awt.Color(56, 61, 70));
        btnFC002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnFC002.setText("Boletos");
        btnFC002.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC002.setFocusPainted(false);
        btnFC002.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC002.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC002.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC002.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC002.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC002.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC002ActionPerformed(evt);
            }
        });

        grupoSubMenuBoletos.setDrawBorder(false);
        grupoSubMenuBoletos.setExpanded(false);
        grupoSubMenuBoletos.setTitleBarVisible(false);

        btnFC005.setBackground(new java.awt.Color(56, 61, 70));
        btnFC005.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnFC005.setText("Envio para representantes");
        btnFC005.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC005.setFocusPainted(false);
        btnFC005.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC005.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC005.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC005.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC005.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC005.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        btnFC006.setBackground(new java.awt.Color(56, 61, 70));
        btnFC006.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnFC006.setText("Envio para clientes");
        btnFC006.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC006.setFocusPainted(false);
        btnFC006.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC006.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC006.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC006.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC006.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC006.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N

        javax.swing.GroupLayout grupoSubMenuBoletosLayout = new javax.swing.GroupLayout(grupoSubMenuBoletos);
        grupoSubMenuBoletos.setLayout(grupoSubMenuBoletosLayout);
        grupoSubMenuBoletosLayout.setHorizontalGroup(
            grupoSubMenuBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFC005, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFC006, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoSubMenuBoletosLayout.setVerticalGroup(
            grupoSubMenuBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoSubMenuBoletosLayout.createSequentialGroup()
                .addComponent(btnFC005, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFC006, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnFC007.setBackground(new java.awt.Color(56, 61, 70));
        btnFC007.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnFC007.setText("Bancos");
        btnFC007.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC007.setFocusPainted(false);
        btnFC007.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC007.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC007.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC007.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC007.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC007.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnFC007.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC007ActionPerformed(evt);
            }
        });

        grupoSubMenuBancos.setDrawBorder(false);
        grupoSubMenuBancos.setExpanded(false);
        grupoSubMenuBancos.setTitleBarVisible(false);

        btnFC008.setBackground(new java.awt.Color(56, 61, 70));
        btnFC008.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 55x40.jpg"))); // NOI18N
        btnFC008.setText("Saldo bancário");
        btnFC008.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC008.setFocusPainted(false);
        btnFC008.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFC008.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFC008.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFC008.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC008.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC008.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 55x40.jpg"))); // NOI18N
        btnFC008.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC008ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grupoSubMenuBancosLayout = new javax.swing.GroupLayout(grupoSubMenuBancos);
        grupoSubMenuBancos.setLayout(grupoSubMenuBancosLayout);
        grupoSubMenuBancosLayout.setHorizontalGroup(
            grupoSubMenuBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFC008, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );
        grupoSubMenuBancosLayout.setVerticalGroup(
            grupoSubMenuBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoSubMenuBancosLayout.createSequentialGroup()
                .addComponent(btnFC008, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout grupoMenuFinanceiroLayout = new javax.swing.GroupLayout(grupoMenuFinanceiro);
        grupoMenuFinanceiro.setLayout(grupoMenuFinanceiroLayout);
        grupoMenuFinanceiroLayout.setHorizontalGroup(
            grupoMenuFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFC001, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
            .addComponent(grupoSubMenuTitulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFC002, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grupoSubMenuBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFC007, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grupoSubMenuBancos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoMenuFinanceiroLayout.setVerticalGroup(
            grupoMenuFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoMenuFinanceiroLayout.createSequentialGroup()
                .addComponent(btnFC001, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoSubMenuTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFC002, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoSubMenuBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFC007, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoSubMenuBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnMT000.setBackground(new java.awt.Color(56, 61, 70));
        btnMT000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_maintenance_40px.png"))); // NOI18N
        btnMT000.setText("Manutenção");
        btnMT000.setColorHover(new java.awt.Color(87, 94, 108));
        btnMT000.setFocusPainted(false);
        btnMT000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMT000.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMT000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMT000ActionPerformed(evt);
            }
        });

        grupoMenuManutencao.setDrawBorder(false);
        grupoMenuManutencao.setExpanded(false);
        grupoMenuManutencao.setTitleBarVisible(false);

        btnMT001.setBackground(new java.awt.Color(56, 61, 70));
        btnMT001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnMT001.setText("Consultar Ferramentas");
        btnMT001.setColorHover(new java.awt.Color(87, 94, 108));
        btnMT001.setFocusPainted(false);
        btnMT001.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMT001.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMT001.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMT001.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT001.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT001.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        btnMT002.setBackground(new java.awt.Color(56, 61, 70));
        btnMT002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnMT002.setText("Vincular Ferramentas");
        btnMT002.setColorHover(new java.awt.Color(87, 94, 108));
        btnMT002.setFocusPainted(false);
        btnMT002.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMT002.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMT002.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMT002.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT002.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT002.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        btnMT003.setBackground(new java.awt.Color(56, 61, 70));
        btnMT003.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnMT003.setText("Cadastrar Ferramentas");
        btnMT003.setColorHover(new java.awt.Color(87, 94, 108));
        btnMT003.setFocusPainted(false);
        btnMT003.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMT003.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMT003.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMT003.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT003.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT003.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        btnMT004.setBackground(new java.awt.Color(56, 61, 70));
        btnMT004.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 40x40.jpg"))); // NOI18N
        btnMT004.setText("Cadastrar Locais");
        btnMT004.setColorHover(new java.awt.Color(87, 94, 108));
        btnMT004.setFocusPainted(false);
        btnMT004.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMT004.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMT004.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMT004.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT004.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N
        btnMT004.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Empty 2 40x40.jpg"))); // NOI18N

        javax.swing.GroupLayout grupoMenuManutencaoLayout = new javax.swing.GroupLayout(grupoMenuManutencao);
        grupoMenuManutencao.setLayout(grupoMenuManutencaoLayout);
        grupoMenuManutencaoLayout.setHorizontalGroup(
            grupoMenuManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMT004, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMT003, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMT002, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMT001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        grupoMenuManutencaoLayout.setVerticalGroup(
            grupoMenuManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoMenuManutencaoLayout.createSequentialGroup()
                .addComponent(btnMT001, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMT002, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMT003, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMT004, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(grupoMenuEstoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnET000, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grupoMenuProducao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPD000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFC000, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMT000, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grupoMenuFinanceiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grupoMenuManutencao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnPD000, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoMenuProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnET000, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoMenuEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFC000, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoMenuFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMT000, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grupoMenuManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 535, Short.MAX_VALUE))
        );

        pnlMenu.setViewportView(jPanel2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logado com:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Geral Zucatoys");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_shield_30px_1.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        pnlHome.setOpaque(false);

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        jPanel1.add(pnlHome, "card3");

        pnlSaldoBancario.setBackground(new java.awt.Color(255, 255, 255));
        pnlSaldoBancario.setOpaque(false);

        jXDatePicker1.setFormats("dd/MM/yyyy");
        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        btnFC008Editar.setBackground(new java.awt.Color(56, 61, 70));
        btnFC008Editar.setText("Editar");
        btnFC008Editar.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC008Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC008EditarActionPerformed(evt);
            }
        });

        btnFC008Salvar.setBackground(new java.awt.Color(56, 61, 70));
        btnFC008Salvar.setText("Salvar");
        btnFC008Salvar.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC008Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC008SalvarActionPerformed(evt);
            }
        });

        tblFC008.setAutoCreateRowSorter(true);
        tblFC008.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblFC008.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código", "Descrição", "Saldo Atual", "Saldo Anterior"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFC008.setEnabled(false);
        tblFC008.setFillsViewportHeight(true);
        tblFC008.setRowHeight(25);
        tblFC008.setSelectionBackground(new java.awt.Color(87, 94, 108));
        jScrollPane1.setViewportView(tblFC008);
        if (tblFC008.getColumnModel().getColumnCount() > 0) {
            tblFC008.getColumnModel().getColumn(0).setMinWidth(0);
            tblFC008.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblFC008.getColumnModel().getColumn(0).setMaxWidth(0);
            tblFC008.getColumnModel().getColumn(1).setMinWidth(80);
            tblFC008.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblFC008.getColumnModel().getColumn(2).setMinWidth(180);
            tblFC008.getColumnModel().getColumn(2).setPreferredWidth(400);
            tblFC008.getColumnModel().getColumn(3).setMinWidth(80);
            tblFC008.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblFC008.getColumnModel().getColumn(4).setMinWidth(80);
            tblFC008.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        btnFC008Consultar.setBackground(new java.awt.Color(56, 61, 70));
        btnFC008Consultar.setText("Consultar");
        btnFC008Consultar.setColorHover(new java.awt.Color(87, 94, 108));
        btnFC008Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFC008ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSaldoBancarioLayout = new javax.swing.GroupLayout(pnlSaldoBancario);
        pnlSaldoBancario.setLayout(pnlSaldoBancarioLayout);
        pnlSaldoBancarioLayout.setHorizontalGroup(
            pnlSaldoBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaldoBancarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSaldoBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlSaldoBancarioLayout.createSequentialGroup()
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnFC008Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFC008Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFC008Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 324, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSaldoBancarioLayout.setVerticalGroup(
            pnlSaldoBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaldoBancarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSaldoBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSaldoBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFC008Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFC008Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFC008Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        jPanel1.add(pnlSaldoBancario, "card2");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPD000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPD000ActionPerformed
        // TODO add your handling code here:
        MenuServices menu = new MenuServices();
        menu.onMenuExpandedAction(grupoMenuProducao, grupoMenuEstoque, grupoMenuFinanceiro, grupoMenuManutencao,
                    grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnPD000ActionPerformed

    private void btnET000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnET000ActionPerformed
        // TODO add your handling code here:
        MenuServices menu = new MenuServices();
        menu.onMenuExpandedAction(grupoMenuEstoque, grupoMenuProducao, grupoMenuFinanceiro, grupoMenuManutencao, 
                grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnET000ActionPerformed

    private void btnFC000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC000ActionPerformed
        // TODO add your handling code here:
        MenuServices menu = new MenuServices();
        menu.onMenuExpandedAction(grupoMenuFinanceiro, grupoMenuProducao, grupoMenuEstoque, grupoMenuManutencao, 
                grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnFC000ActionPerformed

    private void btnMT000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMT000ActionPerformed
        // TODO add your handling code here:
        MenuServices menu = new MenuServices();
        menu.onMenuExpandedAction(grupoMenuManutencao, grupoMenuProducao, grupoMenuEstoque, grupoMenuFinanceiro, 
                grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnMT000ActionPerformed

    private void btnPD001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPD001ActionPerformed
        // TODO add your handling code here:
        MenuServices subMenu = new MenuServices();
        subMenu.onSubMenuExpandedAction(grupoSubMenuInjetora, grupoMenuProducao, grupoMenuEstoque, grupoMenuFinanceiro, grupoMenuManutencao,
                    grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnPD001ActionPerformed

    private void btnPD002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPD002ActionPerformed
        // TODO add your handling code here:
        MenuServices subMenu = new MenuServices();
        subMenu.onSubMenuExpandedAction(grupoSubMenuEmbalagem, grupoMenuProducao, grupoMenuEstoque, grupoMenuFinanceiro, grupoMenuManutencao,
                    grupoSubMenuInjetora, grupoSubMenuTitulos, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnPD002ActionPerformed

    private void btnFC001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC001ActionPerformed
        // TODO add your handling code here:
        MenuServices subMenu = new MenuServices();
        subMenu.onSubMenuExpandedAction(grupoSubMenuTitulos, grupoMenuFinanceiro, grupoMenuProducao, grupoMenuEstoque, grupoMenuManutencao,
                    grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuBoletos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnFC001ActionPerformed

    private void btnFC002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC002ActionPerformed
        // TODO add your handling code here:
        MenuServices subMenu = new MenuServices();
        subMenu.onSubMenuExpandedAction(grupoSubMenuBoletos, grupoMenuFinanceiro, grupoMenuProducao, grupoMenuEstoque, grupoMenuManutencao,
                    grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBancos);
    }//GEN-LAST:event_btnFC002ActionPerformed

    private void btnFC007ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC007ActionPerformed
        // TODO add your handling code here:
        MenuServices subMenu = new MenuServices();
        subMenu.onSubMenuExpandedAction(grupoSubMenuBancos, grupoMenuFinanceiro, grupoMenuProducao, grupoMenuEstoque, grupoMenuManutencao,
                    grupoSubMenuInjetora, grupoSubMenuEmbalagem, grupoSubMenuTitulos, grupoSubMenuBoletos);
    }//GEN-LAST:event_btnFC007ActionPerformed

    private void btnFC008ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC008ActionPerformed
        // TODO add your handling code here:
        this.pnlSaldoBancario.setVisible(true);
    }//GEN-LAST:event_btnFC008ActionPerformed

    private void btnFC008EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC008EditarActionPerformed
        // TODO add your handling code here:
        this.tblFC008.setEnabled(true);
    }//GEN-LAST:event_btnFC008EditarActionPerformed

    private void btnFC008ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC008ConsultarActionPerformed
        // TODO add your handling code here:
        DateService dateService = new DateService();
        TableService ts = new TableService();
        ts.onSetValueTableAction(tblFC008, dateService.formatDate(dateService.formatDate(jXDatePicker1)));
    }//GEN-LAST:event_btnFC008ConsultarActionPerformed

    private void btnFC008SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFC008SalvarActionPerformed
        // TODO add your handling code here:
        DateService dateService = new DateService();
        TableService ts = new TableService();
        ts.onGetValueTableAction(tblFC008, dateService.formatDate(dateService.formatDate(jXDatePicker1)));
        this.tblFC008.setEnabled(false);
    }//GEN-LAST:event_btnFC008SalvarActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
        TableService tableService = new TableService();
        tableService.onDrainOutTableAction(tblFC008);
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnET000;
    private rojerusan.RSButtonHover btnET001;
    private rojerusan.RSButtonHover btnET002;
    private rojerusan.RSButtonHover btnET003;
    private rojerusan.RSButtonHover btnET004;
    private rojerusan.RSButtonHover btnFC000;
    private rojerusan.RSButtonHover btnFC001;
    private rojerusan.RSButtonHover btnFC002;
    private rojerusan.RSButtonHover btnFC003;
    private rojerusan.RSButtonHover btnFC004;
    private rojerusan.RSButtonHover btnFC005;
    private rojerusan.RSButtonHover btnFC006;
    private rojerusan.RSButtonHover btnFC007;
    private rojerusan.RSButtonHover btnFC008;
    private rojerusan.RSButtonHover btnFC008Consultar;
    private rojerusan.RSButtonHover btnFC008Editar;
    private rojerusan.RSButtonHover btnFC008Salvar;
    private rojerusan.RSButtonHover btnMT000;
    private rojerusan.RSButtonHover btnMT001;
    private rojerusan.RSButtonHover btnMT002;
    private rojerusan.RSButtonHover btnMT003;
    private rojerusan.RSButtonHover btnMT004;
    private rojerusan.RSButtonHover btnPD000;
    private rojerusan.RSButtonHover btnPD001;
    private rojerusan.RSButtonHover btnPD002;
    private rojerusan.RSButtonHover btnPD003;
    private rojerusan.RSButtonHover btnPD004;
    private rojerusan.RSButtonHover btnPD005;
    private rojerusan.RSButtonHover btnPD006;
    private com.xzq.osc.JocGroupPane grupoMenuEstoque;
    private com.xzq.osc.JocGroupPane grupoMenuFinanceiro;
    private com.xzq.osc.JocGroupPane grupoMenuManutencao;
    private com.xzq.osc.JocGroupPane grupoMenuProducao;
    private com.xzq.osc.JocGroupPane grupoSubMenuBancos;
    private com.xzq.osc.JocGroupPane grupoSubMenuBoletos;
    private com.xzq.osc.JocGroupPane grupoSubMenuEmbalagem;
    private com.xzq.osc.JocGroupPane grupoSubMenuInjetora;
    private com.xzq.osc.JocGroupPane grupoSubMenuTitulos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JScrollPane pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSaldoBancario;
    private javax.swing.JTable tblFC008;
    // End of variables declaration//GEN-END:variables
}
